### ISSUE TITLE
Dynamo_Toolkit: Polyline issue

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/Dynamo_Toolkit#136] opened 2019-04-23 11:15 UTC
currently Dynamo 1.3 does not support `Polyline` and therefore we lost ability to preview Building, Panels in Dynamo. 
Can we consider Convert `PolyCurve` or I am keen to hear some other work around?

new dynamo 2.1 is out and I could not see significant changes there..

![image](https://user-images.githubusercontent.com/26113670/56576414-3511dc80-65c0-11e9-8855-23c69b6ebffc.png)

![image](https://user-images.githubusercontent.com/26113670/56576576-a6518f80-65c0-11e9-9005-ba150badc7a9.png)

![image](https://user-images.githubusercontent.com/26113670/56576695-fcbece00-65c0-11e9-9fff-dd1ecf6830da.png)

here is some post about this
https://forum.dynamobim.com/t/create-revit-polyline-from-dynamo-polyline/34145
https://dictionary.dynamobim.com/#/Geometry/PolyCurve/Create/ByJoinedCurves

**Comment by FraserGreenroyd** [comment] 2019-04-23 11:30
Have you tried `ToLines`? This is another `Engine.Environment.Convert` method coming in the new PR being tested in addition to `ToPolyline` - maybe that will work better for preview?

**Comment by michaldengusiak** [comment] 2019-04-23 11:31
no I did not... will try now..

**Comment by michaldengusiak** [comment] 2019-04-23 11:41
ok this worked fine for preview

![image](https://user-images.githubusercontent.com/26113670/56577962-4d83f600-65c4-11e9-95f3-e8586f95562d.png)

I did more test and noticed that
when we use BHoM we need to flatten in order to display or we can use native Dynamo node `PolyCurve.ByJoinedCurves`,
![image](https://user-images.githubusercontent.com/26113670/56578180-e0bd2b80-65c4-11e9-8828-dd605053e82c.png)

**Comment by michaldengusiak** [comment] 2019-04-23 11:43
@ZiolkowskiJakub  will this affect anything else we do with geometry ? or this will be fine?

**Comment by IsakNaslundBh** [comment] 2019-04-23 12:11
From just looking at the code, this can probably be fixed by making a IsClosed check and take actions depending on the answer in this method:

https://github.com/BHoM/Dynamo_Toolkit/blob/28f5b15084963132e70cdc8096ae8fdb9adb5c80/Dynamo_Engine/Convert/ToDesignScript.cs#L120-L123

The method used had a boolean option whether to close the curve or not, so that could probably be called, while at the same time removing the duplicate start and endpoints from the BHoM.

**Comment by michaldengusiak** [comment] 2019-04-23 12:26
I spotted now difference
using BHoM
![image](https://user-images.githubusercontent.com/26113670/56580740-2f6dc400-65cb-11e9-904e-13d3b2fbb4dd.png)

using Dynamo, this method gives more accurate representation 
![image](https://user-images.githubusercontent.com/26113670/56580773-48767500-65cb-11e9-9b92-ee27f26cdfad.png)

**Comment by adecler** [comment] 2019-09-26 16:28
@michaldengusiak , could you test if this is still happening? I seems to be working fine for me with a simple rectangular panel by I can't reproduce your example.

I see @IsakNaslundBh  had done a commit to fix this but the branch was never merged.

**Closed** 2020-06-29 14:44 UTC
Labels: type:bug
