### ISSUE TITLE
Native geometry component failing on Revit 2019 version

### ISSUE THREAD

**Issue by adecler** [BHoM/Dynamo_Toolkit#266] opened 2020-09-30 06:40 UTC
#### Description:

Even without the BHoM installed, I got this:

![image](https://user-images.githubusercontent.com/16853390/94651023-571d9b80-032a-11eb-906e-696643392de6.png)

@pawelbaran , @kayleighhoude , do you mind testing on your machine to see if you have the same. Have you seen this before ? Any idea where it might come from ?

**Comment by pawelbaran** [comment] 2020-09-30 08:54
@adecler as discussed, the issue is not related to BHoM as it originates in Dynamo itself. There is a few threads about that on the internet (e.g. [here](https://forum.dynamobim.com/t/the-type-initializer-for-autodesk-libg-libgpinvoke-threw-an-exception/37098/17)), noone knows how or why, usually the suggested solution is updating Dynamo to later version.

I will close this issue based on the above, but please feel free to reopen in the case you believe it needs an action on the BHoM end (or is relevant to BHoM by any other means).

**Closed by pawelbaran** 2020-09-30 08:54 UTC
Labels: type:question
