### ISSUE TITLE
Dynamo_Toolkit: PlanarSurface Conversion

### ISSUE THREAD

**Issue by ZiolkowskiJakub** [BHoM/Dynamo_Toolkit#133] opened 2019-03-18 15:38 UTC

**Comment by michaldengusiak** [comment] 2019-09-13 09:32
would be good to have a look at this, in next sprint

some conversation [here ](https://github.com/BHoM/BHoM_Engine/issues/1196)

![image](https://user-images.githubusercontent.com/26113670/64852646-ab67b780-d611-11e9-8be2-a98f3ba61ad3.png)

**Comment by michaldengusiak** [comment] 2019-09-18 08:00
As we have now Physical approach implemented I come across another issue

when trying to create physical elements it does not work in dynamo. The issue is I can unable to create `PlanasSurface`. We need to adjust a way to generate Surface in dynamo to allow Physical element creation otherwise we are forced to use Grasshopper. 
@IsakNaslundBh @pawelbaran any idea or work around?

![image](https://user-images.githubusercontent.com/26113670/65128967-56051f00-d9f2-11e9-93a0-ad418437a519.png)

![image](https://user-images.githubusercontent.com/26113670/65128995-64533b00-d9f2-11e9-917a-ca102275f73b.png)

**Comment by michaldengusiak** [comment] 2019-09-27 08:40
I will additional [example ](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Dynamo_Toolkit/Dynamo_Toolkit-Issue133-PlanarSurface?csf=1&e=YKBtdp)here  -missing method for BHoM `PlanarSurface `from Dynamo `Surface`

![image](https://user-images.githubusercontent.com/26113670/65755056-47151f80-e10a-11e9-9e74-ddaf82871f22.png)

**Comment by pawelbaran** [comment] 2020-06-29 11:13
This has been resolved with https://github.com/BHoM/Dynamo_Toolkit/pull/247

**Closed by pawelbaran** 2020-06-29 11:13 UTC
Labels: severity:critical, type:bug
