### ISSUE TITLE
Implement Ctrl+Shift+B Search in Dynamo

### ISSUE THREAD

**Issue by kayleighhoude** [BHoM/Dynamo_Toolkit#198] opened 2020-01-17 17:08 UTC
#### Description:
Implement control shift B search feature in Dynamo

**Comment by adecler** [comment] 2020-01-18 04:34
Closing as duplicate of https://github.com/BHoM/Dynamo_Toolkit/issues/146

@kayleighhoude , note that the global menu actually already works in Dynamo Sandbox but not in Dynamo Revit for some reason

**Closed by adecler** 2020-01-18 04:34 UTC
Labels: type:feature
