### ISSUE TITLE
Dynamo_Toolkit: unable to create Construction

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/Dynamo_Toolkit#165] opened 2019-09-18 07:51 UTC
#### Description:

@ZiolkowskiJakub @FraserGreenroyd   not sure who should be assigned here and if this is Dynamo or Engine issue..but I will start here...

in GH we can create construction with name
![image](https://user-images.githubusercontent.com/26113670/65127958-73d18480-d9f0-11e9-96ce-5b27f6d118f4.png)

here it does not work, we do not have any `layer `to create so can not test
I believe we should give in Engine method some default value not `null  `so it supports `Dynamo `
![image](https://user-images.githubusercontent.com/26113670/65128035-95cb0700-d9f0-11e9-9ae7-c0405c536a3f.png)

**Comment by FraserGreenroyd** [comment] 2019-09-18 09:14
I would say this is a Dynamo Toolkit issue bordering on a Dynamo issue - Dynamo/Dynamo Toolkit should be able to handle optional input parameters which are set as `null` on the code side without throwing warnings/errors, so I would advise assigning @ZiolkowskiJakub as the DT dev for him to handle in the next milestone :smile:

**Comment by adecler** [comment] 2019-09-26 16:42
This is a duplicate of issue #90 and is fixed by #170

**Closed by adecler** 2019-09-26 16:42 UTC
Labels: type:bug
